CREATE DATABASE Autopark;

USE Autopark;

CREATE TABLE Cars (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Brand NVARCHAR(50),
	Model NVARCHAR(50),
	[Year] INT,
	Price DECIMAL(18,2)
)

CREATE TABLE Owners (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(50),
	CarId INT FOREIGN KEY REFERENCES Cars(Id)
)
